import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-gray-50">
      <Navbar />

      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

          <div className="prose prose-lg max-w-none">
            <p className="text-gray-500 mb-8">Last updated: July 1, 2023</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
              <p>
                Clientlio ("we," "our," or "us") is committed to protecting your
                privacy. This Privacy Policy explains how we collect, use,
                disclose, and safeguard your information when you visit our
                website or use our AI services.
              </p>
              <p>
                Please read this Privacy Policy carefully. If you do not agree
                with the terms of this Privacy Policy, please do not access the
                site or use our services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                2. Information We Collect
              </h2>
              <p>
                We may collect information about you in a variety of ways,
                including:
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">
                2.1 Personal Data
              </h3>
              <p>
                When you register for an account, we may collect personally
                identifiable information, such as your name, email address,
                company name, and payment information. This information is
                necessary to provide our services and communicate with you.
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">2.2 Usage Data</h3>
              <p>
                We automatically collect information about how you interact with
                our services, including your IP address, browser type, pages
                viewed, time spent on pages, and other browsing information.
                This helps us improve our services and user experience.
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">
                2.3 AI Service Data
              </h3>
              <p>
                When you use our AI services, we collect the data you input
                (such as text for chatbots, customer information for lead
                generation, etc.) and the outputs generated by our AI. This data
                is necessary to provide and improve our AI services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                3. How We Use Your Information
              </h2>
              <p>We may use the information we collect about you to:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Provide, maintain, and improve our services</li>
                <li>Process transactions and send related information</li>
                <li>
                  Send administrative information, such as updates or security
                  alerts
                </li>
                <li>Respond to your comments, questions, and requests</li>
                <li>Develop new products and services</li>
                <li>Monitor and analyze trends, usage, and activities</li>
                <li>
                  Detect, investigate, and prevent fraudulent transactions and
                  other illegal activities
                </li>
                <li>
                  Personalize your experience and deliver content relevant to
                  your interests
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                4. Disclosure of Your Information
              </h2>
              <p>We may share your information in the following situations:</p>

              <h3 className="text-xl font-medium mt-6 mb-3">
                4.1 Service Providers
              </h3>
              <p>
                We may share your information with third-party vendors, service
                providers, and other business partners who perform services on
                our behalf, such as payment processing, data analysis, email
                delivery, and customer service.
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">
                4.2 Legal Requirements
              </h3>
              <p>
                We may disclose your information where required to do so by law
                or in response to valid requests by public authorities (e.g., a
                court or government agency).
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">
                4.3 Business Transfers
              </h3>
              <p>
                We may share or transfer your information in connection with, or
                during negotiations of, any merger, sale of company assets,
                financing, or acquisition of all or a portion of our business to
                another company.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">5. Data Security</h2>
              <p>
                We have implemented appropriate technical and organizational
                security measures designed to protect the security of any
                personal information we process. However, please also remember
                that we cannot guarantee that the internet itself is 100%
                secure.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                6. Your Data Protection Rights
              </h2>
              <p>
                Depending on your location, you may have the following rights:
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  The right to access personal information we hold about you
                </li>
                <li>
                  The right to request correction of inaccurate personal
                  information
                </li>
                <li>
                  The right to request deletion of your personal information
                </li>
                <li>
                  The right to object to processing of your personal information
                </li>
                <li>The right to data portability</li>
                <li>The right to withdraw consent</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">
                7. Changes to This Privacy Policy
              </h2>
              <p>
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page and updating the "Last updated" date.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Contact Us</h2>
              <p>
                If you have questions or comments about this Privacy Policy,
                please contact us at:
              </p>
              <p className="mt-4">
                <strong>Email:</strong> privacy@clientlio.com
                <br />
                <strong>Address:</strong> 123 Market Street, Suite 400, San
                Francisco, CA 94105
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
